name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Navigating to backend directory..."
            cd /home/ec2-user/invoice-apis/CN_MBoss_Backend
            
            echo "Pulling latest changes from main branch..."
            git pull --rebase origin main
            
            echo "Restarting backend service with PM2..."
            pm2 restart mobile-backend-api
            
            echo "Deployment completed successfully!"
